"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Vazirmatn } from "next/font/google";
import SideBar from "@/components/owner/layout/side-bar";
import Header from "@/components/owner/layout/header";
import BackDrop from "@/components/comon/back-drop";
import { useLockBodyScroll } from "@/hooks/use-lock-body-scroll";
import { useEscapeKey } from "@/hooks/use-escape-key";
import { useState } from "react";

const vazirMatn = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const closeMenu = () => setIsMenuOpen(false);

  useLockBodyScroll(isMenuOpen && window.innerWidth < 768);
  useEscapeKey(closeMenu, isMenuOpen);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={`${vazirMatn.variable} antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen w-full bg-bg-main overflow-hidden">
            <BackDrop show={isMenuOpen} onClick={toggleMenu} />
            <SideBar toggleMenu={toggleMenu} isMenuOpen={isMenuOpen} />
            <main className="flex-1 overflow-y-auto">
              <Header isMenuOpen={isMenuOpen} toggleMenu={toggleMenu} />
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
